services:
  sausage-factory-php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - "8000:80"
    depends_on:
      - sausage-factory-mysql

  sausage-factory-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sausage-base
      MYSQL_USER: sausage-man
      MYSQL_PASSWORD: password
    ports:
      - "3320:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
